# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"
ENV["FASTLANE_HIDE_CHANGELOG"] = "true"

platform :android do
  desc "Generate changelog from last version bump/init release to HEAD (reads from version.properties)"
  lane :generate_changelog do
    act_generate_changelog
  end
end
